# Generated by Django 5.1.15 on 2025-12-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_email_c73515_idx',
            old_name='api_email__0a02fd_idx',
        ),
    ]
