# Generated by ChatGPT on 2025-12-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_emailotp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="feed_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="jwt_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_token_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_token_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_token_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="token_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="token_state",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
