# Generated by GitHub Copilot on 2025-12-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instrument", models.CharField(choices=[("NIFTY", "Nifty 50"), ("BANKNIFTY", "Nifty Bank"), ("SENSEX", "Sensex")], max_length=16, unique=True)),
                ("contract_expiry", models.DateField(blank=True, null=True)),
                ("contract_expiry_code", models.CharField(blank=True, default="", max_length=16)),
                ("transaction", models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], default="BUY", max_length=4)),
                ("no_of_lots", models.PositiveIntegerField(default=0)),
                ("pl_exit_lots", models.PositiveIntegerField(default=0)),
                ("premium_price", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("pl_points", models.IntegerField(default=0)),
                ("sl_points", models.IntegerField(default=0)),
                ("trailing_points", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["instrument"]},
        ),
    ]
