# Generated by GitHub Copilot on 2025-12-07
from django.db import migrations


def create_default_instruments(apps, schema_editor):
    Instrument = apps.get_model("api", "Instrument")

    defaults = [
        ("NIFTY", {"transaction": "BUY", "no_of_lots": 1, "pl_exit_lots": 1}),
        ("BANKNIFTY", {"transaction": "BUY", "no_of_lots": 1, "pl_exit_lots": 1}),
        ("SENSEX", {"transaction": "BUY", "no_of_lots": 1, "pl_exit_lots": 1}),
    ]

    for instrument_code, extra in defaults:
        Instrument.objects.get_or_create(
            instrument=instrument_code,
            defaults={
                "no_of_lots": extra.get("no_of_lots", 0),
                "pl_exit_lots": extra.get("pl_exit_lots", 0),
                "transaction": extra.get("transaction", "BUY"),
            },
        )


def remove_default_instruments(apps, schema_editor):
    Instrument = apps.get_model("api", "Instrument")
    Instrument.objects.filter(instrument__in=["NIFTY", "BANKNIFTY", "SENSEX"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_instrument"),
    ]

    operations = [
        migrations.RunPython(create_default_instruments, reverse_code=remove_default_instruments),
    ]
