# Generated by Django 5.1.15 on 2025-12-06 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_instruments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_email_d57b6f_idx',
            old_name='api_emailot_email_purpose_is_used_idx',
        ),
        migrations.AddField(
            model_name='instrument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Nifty Bank'), ('SENSEX', 'Sensex')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('user', 'instrument'), name='unique_instrument_per_user'),
        ),
    ]
