# Generated by GitHub Copilot on 2025-12-07
from __future__ import annotations

from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def initialize_user_instruments(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Instrument = apps.get_model("api", "Instrument")

    try:
        from api.constants import INSTRUMENT_PRESETS
        from api.utils.instrument_data import (
            ensure_parent_directories,
            load_expiry_map,
            next_valid_expiry,
            parse_expiry_code,
        )
    except Exception:
        INSTRUMENT_PRESETS = {}
        ensure_parent_directories = None
        load_expiry_map = None
        next_valid_expiry = None
        parse_expiry_code = None

    expiry_map = {}
    if ensure_parent_directories and load_expiry_map:
        try:
            ensure_parent_directories()
            expiry_map = load_expiry_map()
        except Exception:
            expiry_map = {}

    today = timezone.now().date()

    Instrument.objects.filter(user__isnull=True).delete()

    for user in User.objects.all():
        for code, defaults in INSTRUMENT_PRESETS.items():
            options = expiry_map.get(code, []) if expiry_map else []
            selection_code = ""
            selection_date = None
            if options and next_valid_expiry and parse_expiry_code:
                next_code = next_valid_expiry(options, today)
                next_date = parse_expiry_code(next_code) if next_code else None
                if next_code and next_date:
                    selection_code = next_code
                    selection_date = next_date

            payload = {
                "transaction": defaults["transaction"],
                "no_of_lots": defaults["no_of_lots"],
                "pl_exit_lots": defaults["pl_exit_lots"],
                "premium_price": Decimal(str(defaults["premium_price"])),
                "pl_points": defaults["pl_points"],
                "sl_points": defaults["sl_points"],
                "trailing_points": defaults["trailing_points"],
                "active": defaults["active"],
                "contract_expiry_code": selection_code,
                "contract_expiry": selection_date,
            }

            Instrument.objects.update_or_create(
                user=user,
                instrument=code,
                defaults=payload,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_api_emailot_email_purpose_is_used_idx_api_emailot_email_d57b6f_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(initialize_user_instruments, reverse_code=noop),
    ]
