# Generated by Django 5.1.15 on 2025-12-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_initialize_user_instruments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='user',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL),
        ),
    ]
