# Generated by GitHub Copilot on 2025-12-07
from django.db import migrations


def set_nifty_lots_to_one(apps, schema_editor):
    Instrument = apps.get_model("api", "Instrument")
    Instrument.objects.filter(instrument="NIFTY").update(no_of_lots=1)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_instrument_user"),
    ]

    operations = [
        migrations.RunPython(set_nifty_lots_to_one, migrations.RunPython.noop),
    ]
