# Generated by hand
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_strategy_activation(apps, schema_editor):
    StrategyActivation = apps.get_model("api", "StrategyActivation")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    for user in User.objects.all():
        StrategyActivation.objects.get_or_create(user=user, strategy_code="strategy_alpha")


def create_algo_configuration(apps, schema_editor):
    AlgoConfiguration = apps.get_model("api", "AlgoConfiguration")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    for user in User.objects.all():
        AlgoConfiguration.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_update_nifty_default_lots"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgoConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("algo_active", models.BooleanField(default=False)),
                ("market_active", models.BooleanField(default=False)),
                ("market_active_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="algo_configuration", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Algo Configuration",
                "verbose_name_plural": "Algo Configurations",
            },
        ),
        migrations.CreateModel(
            name="StrategyActivation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("strategy_code", models.CharField(choices=[("strategy_alpha", "Strategy Alpha")], max_length=64)),
                ("is_active", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="strategy_activations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Strategy Activation",
                "verbose_name_plural": "Strategy Activations",
                "unique_together": {("user", "strategy_code")},
            },
        ),
        migrations.CreateModel(
            name="StrategyActivationInstrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("activation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="instrument_links", to="api.strategyactivation")),
                ("instrument", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activation_links", to="api.instrument")),
            ],
            options={
                "verbose_name": "Strategy Activation Instrument",
                "verbose_name_plural": "Strategy Activation Instruments",
                "unique_together": {("activation", "instrument")},
            },
        ),
        migrations.AddField(
            model_name="strategyactivation",
            name="selected_instruments",
            field=models.ManyToManyField(blank=True, related_name="strategy_activations", through="api.StrategyActivationInstrument", to="api.instrument"),
        ),
        migrations.RunPython(create_algo_configuration, migrations.RunPython.noop),
        migrations.RunPython(create_strategy_activation, migrations.RunPython.noop),
    ]
