# Generated by ChatGPT on 2025-12-07
from __future__ import annotations

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_algo_strategy_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyactivation",
            name="execution_mode",
            field=models.CharField(
                choices=[("demo", "Demo"), ("live", "Live")],
                default="demo",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="StrategyRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_logs",
                        to="api.strategyactivation",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_code",
                    models.CharField(max_length=64),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("demo", "Demo"), ("live", "Live")],
                        default="demo",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=4,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "entry_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "exit_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "entry_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "exit_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "target_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "trailing_stop_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "last_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                    ),
                ),
                ("external_entry_id", models.CharField(blank=True, max_length=64)),
                ("external_exit_id", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="api.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_datetime", "-created_at"],
            },
        ),
    ]
