# Generated by ChatGPT on 2025-12-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_strategy_execution_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="exchange",
            field=models.CharField(blank=True, default="NFO", max_length=16),
        ),
        migrations.AddField(
            model_name="instrument",
            name="lot_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instrument",
            name="symbol_token",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="instrument",
            name="trading_symbol",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
