# Generated by Django 5.1.15 on 2025-12-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_update_lot_sizes_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='alternate_symbol_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='instrument',
            name='alternate_trading_symbol',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_symbol',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trade',
            name='contract_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
