from decimal import Decimal

INSTRUMENT_PRESETS = {
    "NIFTY": {
        "transaction": "BUY",
        "no_of_lots": 1,
        "pl_exit_lots": 1,
        "premium_price": Decimal("200"),
        "pl_points": 45,
        "sl_points": 35,
        "trailing_points": 15,
        "active": False,
        "exchange": "NFO",
        "lot_size": 75,
        "trading_symbol": "",
        "symbol_token": "",
        "strike_selection": "atm",
        "strike_step": 50,
        "ce_strike_offset": 0,
        "pe_strike_offset": 0,
    },
    "BANKNIFTY": {
        "transaction": "BUY",
        "no_of_lots": 1,
        "pl_exit_lots": 1,
        "premium_price": Decimal("500"),
        "pl_points": 50,
        "sl_points": 50,
        "trailing_points": 10,
        "active": False,
        "exchange": "NFO",
        "lot_size": 35,
        "trading_symbol": "",
        "symbol_token": "",
        "strike_selection": "atm",
        "strike_step": 100,
        "ce_strike_offset": 0,
        "pe_strike_offset": 0,
    },
    "SENSEX": {
        "transaction": "BUY",
        "no_of_lots": 1,
        "pl_exit_lots": 1,
        "premium_price": Decimal("400"),
        "pl_points": 40,
        "sl_points": 35,
        "trailing_points": 12,
        "active": False,
        "exchange": "BFO",
        "lot_size": 20,
        "trading_symbol": "",
        "symbol_token": "",
        "strike_selection": "atm",
        "strike_step": 100,
        "ce_strike_offset": 0,
        "pe_strike_offset": 0,
    },
}
